version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a_root_pw
      MYSQL_USER: a_user
      MYSQL_PASSWORD: a_password
      MYSQL_DATABASE: a_db
    ports:
      - 3306:3306
  nginx:
    build:
      context: .
      dockerfile: Dockerfile/nginx
    ports:
      - 1980:80
  fpm:
    build: 
      context: .
      dockerfile: Dockerfile/fpm
