apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpfpm
  name: phpfpm
spec:
  ports:
  - name: phpfpm
    port: 9000
    targetPort: 9000
  selector:
    app: phpfpm
status:
  loadBalancer: {}
